/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Indicates a credit card's brand, such as `VISA` or `MASTERCARD`.
 */
public enum CardBrand {
  
  OTHER_BRAND("OTHER_BRAND"),
  
  VISA("VISA"),
  
  MASTERCARD("MASTERCARD"),
  
  AMERICAN_EXPRESS("AMERICAN_EXPRESS"),
  
  DISCOVER("DISCOVER"),
  
  DISCOVER_DINERS("DISCOVER_DINERS"),
  
  JCB("JCB"),
  
  CHINA_UNIONPAY("CHINA_UNIONPAY"),
  
  SQUARE_GIFT_CARD("SQUARE_GIFT_CARD");

  private String value;

  CardBrand(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static CardBrand fromValue(String text) {
    for (CardBrand b : CardBrand.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

