/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * 
 */
@ApiModel(description = "")

public class CatalogQueryCustomAttributeUsage {
  @JsonProperty("custom_attribute_definition_ids")
  private List<String> customAttributeDefinitionIds = new ArrayList<String>();

  @JsonProperty("has_value")
  private Boolean hasValue = null;

  public CatalogQueryCustomAttributeUsage customAttributeDefinitionIds(List<String> customAttributeDefinitionIds) {
    this.customAttributeDefinitionIds = customAttributeDefinitionIds;
    return this;
  }

  public CatalogQueryCustomAttributeUsage addCustomAttributeDefinitionIdsItem(String customAttributeDefinitionIdsItem) {
    this.customAttributeDefinitionIds.add(customAttributeDefinitionIdsItem);
    return this;
  }

   /**
   * 
   * @return customAttributeDefinitionIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getCustomAttributeDefinitionIds() {
    return customAttributeDefinitionIds;
  }

  public void setCustomAttributeDefinitionIds(List<String> customAttributeDefinitionIds) {
    this.customAttributeDefinitionIds = customAttributeDefinitionIds;
  }

  public CatalogQueryCustomAttributeUsage hasValue(Boolean hasValue) {
    this.hasValue = hasValue;
    return this;
  }

   /**
   * 
   * @return hasValue
  **/
  @ApiModelProperty(value = "")
  public Boolean getHasValue() {
    return hasValue;
  }

  public void setHasValue(Boolean hasValue) {
    this.hasValue = hasValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CatalogQueryCustomAttributeUsage catalogQueryCustomAttributeUsage = (CatalogQueryCustomAttributeUsage) o;
    return Objects.equals(this.customAttributeDefinitionIds, catalogQueryCustomAttributeUsage.customAttributeDefinitionIds) &&
        Objects.equals(this.hasValue, catalogQueryCustomAttributeUsage.hasValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customAttributeDefinitionIds, hasValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CatalogQueryCustomAttributeUsage {\n");
    
    sb.append("    customAttributeDefinitionIds: ").append(toIndentedString(customAttributeDefinitionIds)).append("\n");
    sb.append("    hasValue: ").append(toIndentedString(hasValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

