/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;


/**
 * Possible kinds of [CatalogObject](#type-catalogobject)s returned from the Catalog, each contaning type-specific properties in the `*_data` field corresponding to the object type.
 */
public enum CatalogObjectType {
  
  @SerializedName("ITEM")
  ITEM("ITEM"),
  
  @SerializedName("CATEGORY")
  CATEGORY("CATEGORY"),
  
  @SerializedName("ITEM_VARIATION")
  ITEM_VARIATION("ITEM_VARIATION"),
  
  @SerializedName("TAX")
  TAX("TAX"),
  
  @SerializedName("DISCOUNT")
  DISCOUNT("DISCOUNT"),
  
  @SerializedName("MODIFIER_LIST")
  MODIFIER_LIST("MODIFIER_LIST"),
  
  @SerializedName("MODIFIER")
  MODIFIER("MODIFIER");

  private String value;

  CatalogObjectType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }
}

