/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Indicates how the inventory change was applied to a tracked quantity of items.
 */
public enum InventoryChangeType {
  
  PHYSICAL_COUNT("PHYSICAL_COUNT"),
  
  ADJUSTMENT("ADJUSTMENT"),
  
  TRANSFER("TRANSFER");

  private String value;

  InventoryChangeType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static InventoryChangeType fromValue(String text) {
    for (InventoryChangeType b : InventoryChangeType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

