/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Unit of area used to measure a quantity.
 */
public enum MeasurementUnitArea {
  
  IMPERIAL_ACRE("IMPERIAL_ACRE"),
  
  IMPERIAL_SQUARE_INCH("IMPERIAL_SQUARE_INCH"),
  
  IMPERIAL_SQUARE_FOOT("IMPERIAL_SQUARE_FOOT"),
  
  IMPERIAL_SQUARE_YARD("IMPERIAL_SQUARE_YARD"),
  
  IMPERIAL_SQUARE_MILE("IMPERIAL_SQUARE_MILE"),
  
  METRIC_SQUARE_CENTIMETER("METRIC_SQUARE_CENTIMETER"),
  
  METRIC_SQUARE_METER("METRIC_SQUARE_METER"),
  
  METRIC_SQUARE_KILOMETER("METRIC_SQUARE_KILOMETER");

  private String value;

  MeasurementUnitArea(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MeasurementUnitArea fromValue(String text) {
    for (MeasurementUnitArea b : MeasurementUnitArea.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

