/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * The unit of volume used to measure a quantity.
 */
public enum MeasurementUnitVolume {
  
  GENERIC_FLUID_OUNCE("GENERIC_FLUID_OUNCE"),
  
  GENERIC_SHOT("GENERIC_SHOT"),
  
  GENERIC_CUP("GENERIC_CUP"),
  
  GENERIC_PINT("GENERIC_PINT"),
  
  GENERIC_QUART("GENERIC_QUART"),
  
  GENERIC_GALLON("GENERIC_GALLON"),
  
  IMPERIAL_CUBIC_INCH("IMPERIAL_CUBIC_INCH"),
  
  IMPERIAL_CUBIC_FOOT("IMPERIAL_CUBIC_FOOT"),
  
  IMPERIAL_CUBIC_YARD("IMPERIAL_CUBIC_YARD"),
  
  METRIC_MILLILITER("METRIC_MILLILITER"),
  
  METRIC_LITER("METRIC_LITER");

  private String value;

  MeasurementUnitVolume(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static MeasurementUnitVolume fromValue(String text) {
    for (MeasurementUnitVolume b : MeasurementUnitVolume.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

