/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Indicates whether this is a line item or order-level discount.
 */
public enum OrderLineItemDiscountScope {
  
  LINE_ITEM("LINE_ITEM"),
  
  ORDER("ORDER");

  private String value;

  OrderLineItemDiscountScope(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static OrderLineItemDiscountScope fromValue(String text) {
    for (OrderLineItemDiscountScope b : OrderLineItemDiscountScope.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

