/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Whether to the tax amount should be additional to or included in to the [CatalogItem](#type-catalogitem) price.
 */
public enum TaxInclusionType {
  
  ADDITIVE("ADDITIVE"),
  
  INCLUSIVE("INCLUSIVE");

  private String value;

  TaxInclusionType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TaxInclusionType fromValue(String text) {
    for (TaxInclusionType b : TaxInclusionType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

