/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.squareup.connect.models.Location;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Request object for the [UpdateLocation](#endpoint-updatelocation) endpoint.
 */
@ApiModel(description = "Request object for the [UpdateLocation](#endpoint-updatelocation) endpoint.")

public class UpdateLocationRequest {
  @JsonProperty("location")
  private Location location = null;

  public UpdateLocationRequest location(Location location) {
    this.location = location;
    return this;
  }

   /**
   * The `Location` object with only the fields to update.
   * @return location
  **/
  @ApiModelProperty(value = "The `Location` object with only the fields to update.")
  public Location getLocation() {
    return location;
  }

  public void setLocation(Location location) {
    this.location = location;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateLocationRequest updateLocationRequest = (UpdateLocationRequest) o;
    return Objects.equals(this.location, updateLocationRequest.location);
  }

  @Override
  public int hashCode() {
    return Objects.hash(location);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateLocationRequest {\n");
    
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

