/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * 
 */
public enum V1PaymentItemizationItemizationType {
  
  ITEM("ITEM"),
  
  CUSTOM_AMOUNT("CUSTOM_AMOUNT"),
  
  GIFT_CARD_ACTIVATION("GIFT_CARD_ACTIVATION"),
  
  GIFT_CARD_RELOAD("GIFT_CARD_RELOAD"),
  
  GIFT_CARD_UNKNOWN("GIFT_CARD_UNKNOWN"),
  
  OTHER("OTHER");

  private String value;

  V1PaymentItemizationItemizationType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static V1PaymentItemizationItemizationType fromValue(String text) {
    for (V1PaymentItemizationItemizationType b : V1PaymentItemizationItemizationType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

