/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * 
 */
public enum V1SettlementEntryType {
  
  ADJUSTMENT("ADJUSTMENT"),
  
  BALANCE_CHARGE("BALANCE_CHARGE"),
  
  CHARGE("CHARGE"),
  
  FREE_PROCESSING("FREE_PROCESSING"),
  
  HOLD_ADJUSTMENT("HOLD_ADJUSTMENT"),
  
  PAID_SERVICE_FEE("PAID_SERVICE_FEE"),
  
  PAID_SERVICE_FEE_REFUND("PAID_SERVICE_FEE_REFUND"),
  
  REDEMPTION_CODE("REDEMPTION_CODE"),
  
  REFUND("REFUND"),
  
  RETURNED_PAYOUT("RETURNED_PAYOUT"),
  
  SQUARE_CAPITAL_ADVANCE("SQUARE_CAPITAL_ADVANCE"),
  
  SQUARE_CAPITAL_PAYMENT("SQUARE_CAPITAL_PAYMENT"),
  
  SQUARE_CAPITAL_REVERSED_PAYMENT("SQUARE_CAPITAL_REVERSED_PAYMENT"),
  
  SUBSCRIPTION_FEE("SUBSCRIPTION_FEE"),
  
  SUBSCRIPTION_FEE_REFUND("SUBSCRIPTION_FEE_REFUND"),
  
  OTHER("OTHER"),
  
  INCENTED_PAYMENT("INCENTED_PAYMENT"),
  
  RETURNED_ACH_ENTRY("RETURNED_ACH_ENTRY"),
  
  RETURNED_SQUARE_275("RETURNED_SQUARE_275"),
  
  SQUARE_275("SQUARE_275"),
  
  SQUARE_CARD("SQUARE_CARD");

  private String value;

  V1SettlementEntryType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static V1SettlementEntryType fromValue(String text) {
    for (V1SettlementEntryType b : V1SettlementEntryType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

