/*
 * Square Connect API
 * Client library for accessing the Square Connect APIs
 *
 * OpenAPI spec version: 2.0
 * Contact: developers@squareup.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.squareup.connect.models;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * 
 */
public enum V1TenderType {
  
  CREDIT_CARD("CREDIT_CARD"),
  
  CASH("CASH"),
  
  THIRD_PARTY_CARD("THIRD_PARTY_CARD"),
  
  NO_SALE("NO_SALE"),
  
  SQUARE_WALLET("SQUARE_WALLET"),
  
  SQUARE_GIFT_CARD("SQUARE_GIFT_CARD"),
  
  UNKNOWN("UNKNOWN"),
  
  OTHER("OTHER");

  private String value;

  V1TenderType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static V1TenderType fromValue(String text) {
    for (V1TenderType b : V1TenderType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

